---
- hosts: frontend
  become: true
  tasks:
    - name: install apache httpd
      ansible.builtin.dnf:
       name: httpd
       state: absent
       update_cache: yes
    # - name: run server
    #   ansible.builtin.service:
    #    name: httpd
    #    state: started
    - name: copy file with owner andpermissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'